tracer: Fix TestMalformedTID so it passes on its own
This test appears to be depending on previous tests because it does
not pass when run on its own:

$ go test ./ddtrace/tracer -run=TestMalformedTID

--- FAIL: TestMalformedTID (0.01s)
    textmap_test.go:2079:
          Error Trace:  /Users/evan.jones/dd/dd-trace-go/ddtrace/tracer/textmap_test.go:2079
          Error:        Not equal:
                        expected: "640cfd8d00000000"
                        actual  : ""

Fix the test:
* Call internal.SetGlobalTracer(tracer) which is required for the
  test to pass.
* Create assert objects in the sub tests so the correct tests fail.
* Do not set the headerPropagationStyleExtract environment variable.
  It does not seem to be required.

Additionally, while fixing this test I noticed similar problems in
TestTracerStartSpanOptions128:
* Create the assert object in each subtest so the correct test fails
* defer internal.SetGlobalTracer(&internal.NoopTracer{}) to ensure
  this test does not accidentally affect other tests.